#
# Copyright (c) 2026 Fraunhofer-Gesellschaft zur Foerderung der angewandten Forschung e.V. (represented by Fraunhofer ISST)
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

services:
  shared-postgres:
    container_name: shared-postgres
    image: postgres:16.4-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./additional_config/pg_init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -h 127.0.0.1 || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 20
    networks:
      - con-x-test-network

  shared-vault:
    container_name: shared-vault
    image: vault:1.13.3
    # image: vault:1.21
    command: vault server -config=/vault/config/vault.hcl
    volumes:
        - ./vault/data:/vault/data
        - ./vault/config:/vault/config
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      SKIP_SETCAP: "true"
      SKIP_CHOWN: "true"
    healthcheck:
      test: ["CMD", "sh", "-c", "VAULT_ADDR=http://127.0.0.1:8200 vault status >/dev/null 2>&1"]
      interval: 4s
      timeout: 3s
      retries: 20
    ports:
      - "8200:8200"
    networks:
      - con-x-test-network
      - proxy

  vault-init:
    container_name: vault-init
    image: alpine:3.19
    depends_on:
      shared-vault:
        condition: service_healthy
    environment:
      VAULT_ADDR: http://shared-vault:8200
      VAULT_TOKEN: ${VAULT_TOKEN}
    volumes:
      - ./additional_config/vault-init.sh:/scripts/init.sh:ro

    entrypoint: [
      "sh", "-c",
      "apk add --no-check-certificate --no-cache curl jq openssl \
       && tr -d '\r' < /scripts/init.sh > /tmp/init.sh \
       && sh /tmp/init.sh"
    ]
    restart: "no"
    networks:
      - con-x-test-network

  provider-wallet:
    container_name: provider-wallet
    image: ghcr.io/project-construct-x/wallet:0.17.0-1
    pull_policy: missing
    depends_on:
      shared-postgres:
        condition: service_healthy
      vault-init:
        condition: service_completed_successfully
    ports:
      - "1046:1045"         # debugger
      - "21000:80"          # did API           -> /
      - "21100:15151"       # identity API      -> /api/identity
      - "21500:9292"        # sts API           -> /api/sts
      - "21600:13131"       # credentials API   -> /api/credentials
    # - "10200:15152"       # issueradmin API   -> /api/issuer
    # - "13132:13132"       # issuance API      -> /api/issuance
    #      - "8181:8181"        # default API       -> /api
    #      - "9999:9999"        # statuslist API    -> /statuslist
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:1045
      - EDC_HOSTNAME=${DOMAIN}
      - EDC_IAM_DID_WEB_USE_HTTPS=true
      - EDC_ISSUER_ISSUANCE_SEND_RETRY_LIMIT=0
      - EDC_IAM_CREDENTIAL_RENEWAL_GRACEPERIOD=172800
      - EDC_IH_API_SUPERUSER_ID=admin
      - EDC_IH_API_KEY_SUPERUSER=YWRtaW4.adminKey
      - EDC_ISSUER_STATUSLIST_SIGNING_KEY_ALIAS=foo
      - EDC_ENCRYPTION_AES_KEY_ALIAS=provider-wallet-aes-key-alias
      - EDC_IAM_KEY_ALGORITHM=RSA
      - EDC_IH_API_SUPERUSER_PUBLIC_KEY_ALIAS=admin3#pubkey
      - EDC_IH_API_SUPERUSER_PRIVATE_KEY_ALIAS=admin3#privkey
      - WEB_HTTP_DID_PORT=80
      - EDC_SQL_SCHEMA_AUTOCREATE=true
      - EDC_DATASOURCE_DEFAULT_URL=jdbc:postgresql://shared-postgres:5432/prov_ih_db
      - EDC_DATASOURCE_DEFAULT_USER=admin
      - EDC_DATASOURCE_DEFAULT_PASSWORD=password
      - EDC_VAULT_HASHICORP_URL=http://shared-vault:8200
      - EDC_VAULT_HASHICORP_HEALTH_CHECK_ENABLED=true
      - EDC_VAULT_HASHICORP_TOKEN=${VAULT_TOKEN}
      - EDC_STATUSLIST_CALLBACK_ADDRESS=https://${DOMAIN}/statuslist
    networks:
      - con-x-test-network
      - proxy

  provider-controlplane:
    container_name: provider-controlplane
    image: ghcr.io/project-construct-x/con-x-controlplane-postgresql-hashicorp-vault:latest
    pull_policy: missing
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005
      - tx.edc.postgresql.migration.asset.enabled=false
      - tx.edc.postgresql.migration.agreementbpns.enabled=false
      - tx.edc.postgresql.migration.bpn.enabled=false
      - tx.edc.postgresql.migration.contractdefinition.enabled=false
      - tx.edc.postgresql.migration.contractnegotiation.enabled=false
      - tx.edc.postgresql.migration.dataplaneinstance.enabled=false
      - tx.edc.postgresql.migration.edr.enabled=false
      - tx.edc.postgresql.migration.federatedcatalog.enabled=false
      - tx.edc.postgresql.migration.jti-validation.enabled=false
      - tx.edc.postgresql.migration.policy-monitor.enabled=false
      - tx.edc.postgresql.migration.policy.enabled=false
      - tx.edc.postgresql.migration.transferprocess.enabled=false
      - edc.iam.trusted-issuer.example.id=${ISSUER_DID}
      - edc.iam.did.web.use.https=true
      - edc.iam.sts.oauth.client.secret.alias=consumersecret
      - edc.iam.credential.revocation.mimetype=application/json
      - edc.iam.sts.oauth.token.url=http://provider-wallet:9292/api/sts/token
      - edc.iam.sts.oauth.client.id=${DID}
      - edc.iam.issuer.id=${DID}
      - web.http.port=9000
      - web.http.path=/api
      - web.http.management.port=9010
      - web.http.management.path=/management
      - web.http.management.auth.key=prov-management-api-key
      - web.http.management.auth.type=tokenbased
      - web.http.protocol.port=9020
      - web.http.protocol.path=/dsp
      - web.http.validation.port=9030
      - web.http.validation.path=/validation
      - web.http.control.port=9050
      - web.http.control.path=/cpcontrol
      - edc.hostname=${DOMAIN}
      - edc.participant.id=${DID}
      - edc.dsp.callback.address=https://${DOMAIN}/dsp
      - edc.sql.schema.autocreate=true
      - edc.datasource.default.url=jdbc:postgresql://shared-postgres:5432/prov_cpl
      - edc.datasource.default.user=admin
      - edc.datasource.default.password=password
      - edc.vault.hashicorp.url=http://shared-vault:8200
      - edc.vault.hashicorp.health.check.enabled=true
      - edc.vault.hashicorp.token=${VAULT_TOKEN}
      - tx.edc.iam.iatp.default-scopes.test.alias=org.eclipse.dspace.dcp.vc.type
      - tx.edc.iam.iatp.default-scopes.test.type=MembershipCredential
      - tx.edc.iam.iatp.default-scopes.test.operation=read
      - edc.vault.hashicorp.token.scheduled-renew-enabled=false
    healthcheck:
      test: [ "CMD-SHELL", "wget --spider http://localhost:9000/api/check/readiness || exit 1" ]
      start_period: 10s
      interval: 3s
      retries: 30
    depends_on:
        shared-postgres:
          condition: service_healthy
        vault-init:
          condition: service_completed_successfully
    entrypoint: [ "java", "-jar", "edc-runtime.jar", "--log-level=DEBUG" ]
    ports:
      - "5006:5005"   # Debugger
      - "39000:9000"  # Default port
      - "39010:9010"  # Management API
      - "39020:9020" # DSP API
    networks:
      - con-x-test-network
      - proxy

  provider-dataplane:
    container_name: provider-dataplane
    image: ghcr.io/project-construct-x/con-x-dataplane-postgresql-hashicorp-vault:latest
    pull_policy: missing
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5005
      - web.http.public.port=9500
      - web.http.public.path=/public
      - web.http.management.port=9510
      - web.http.management.path=/management
      - web.http.control.port=9550
      - web.http.control.path=/dpcontrol
      - edc.hostname=provider-dataplane
      - edc.dpf.selector.url=https://${DOMAIN}/cpcontrol/v1/dataplanes
      - edc.data.plane.self.unregistration=true
      - edc.datasource.default.url=jdbc:postgresql://shared-postgres:5432/prov_dpl
      - edc.datasource.default.user=admin
      - edc.datasource.default.password=password
      - edc.sql.schema.autocreate=true
      - edc.transfer.proxy.token.signer.privatekey.alias=prov_priv
      - edc.transfer.proxy.token.verifier.publickey.alias=prov_pub
      - edc.vault.hashicorp.url=http://shared-vault:8200
      - edc.vault.hashicorp.health.check.enabled=true
      - edc.vault.hashicorp.token=${VAULT_TOKEN}
      - edc.iam.trusted-issuer.example.id=${ISSUER_DID}
      - edc.iam.did.web.use.https=true
      - edc.iam.sts.oauth.client.secret.alias=consumersecret
      - edc.iam.credential.revocation.mimetype=application/json
      - edc.iam.sts.oauth.token.url=http://provider-wallet:9292/api/sts/token
      - edc.iam.sts.oauth.client.id=${DID}
      - edc.iam.issuer.id=${DID}
      - edc.dataplane.api.public.baseurl=https://${DOMAIN}/public
      - edc.vault.hashicorp.token.scheduled-renew-enabled=false
    depends_on:
      provider-controlplane:
        condition: service_healthy
    entrypoint: [ "java", "-jar", "edc-runtime.jar", "--log-level=DEBUG" ]
    ports:
      - "5007:5005"   # Debugger
      - "9500:9500" # Public API
    networks:
      - con-x-test-network
      - proxy

networks:
  con-x-test-network:
    name: con-x-test-network
    driver: bridge
  proxy:
    external: true

volumes:
  pgdata: